### ISSUE TITLE
Discover census/ACS datasets that correlate with indicators

### ISSUE THREAD

**Issue by jtkovacs** [uwescience/DSSG2017-Equity#10]
Discover census/ACS datasets that correlate with indicators

**Comment by bernease** [comment]
Links from Tuesday morning's demo:

### General

https://www.census.gov/data/developers/data-sets/acs-5year.html

### Example list
http://api.census.gov/data/2015/acs5/examples.html

### Handcrafted example
http://api.census.gov/data/2015/acs5?get=NAME,B01001_001E&for=block+group:*&in=state:53&in=county:033

**Comment by mayahui** [comment]
Data dictionary of ACS 2015:

https://www.socialexplorer.com/data/ACS2015_5yr/metadata/?ds=ACS15_5yr
