### ISSUE TITLE
Deal with different geometry granularities

### ISSUE THREAD

**Issue by bernease** [uwescience/DSSG2017-Equity#14]
@jamr444 and @hillary-dawkins,

I think the best plan of action on the multiple geometries is to create multiple files, a `neighborhoods.csv`, `tracts.csv`, and `block_groups.csv` that hold the data at different levels. This would mean that the crosswalk script outputs the info at all three levels. Also, we may want to generalize the crosswalks script to work with non-Census data as well. That way, we can easily populate the three files when we find outside data at any one of those levels.

**Comment by bernease** [comment]
So @hillary-dawkins, I'd go ahead and make the assumption that you can find the data in any one of these three files. Feel free to make an example file (even with random numbers!) to test the setup before we get crosswalks script running.

**Comment by bernease** [comment]
Example of acs upload script output (thanks to @mayahui):  https://github.com/uwescience/DSSG2017-Equity/blob/gh-pages/data/scripts/outputs/acs_block_data.json

Example of crosswalks script output: https://github.com/uwescience/DSSG2017-Equity/blob/gh-pages/data/scripts/outputs/acs_tract_data2_neighborhood.csv

**Comment by hillary-dawkins** [comment]
@jamr444 I added a csv file on the dev-pages branch under data which has all the blocks in the city labelled by geoid and their land and water area. I assume we want to filter and use only the land blocks? But for completeness they're all there for now.

**Comment by bernease** [comment]
This is done. Thanks to @mayahui.
