### ISSUE TITLE
Sources links seem to all point to `self`

### ISSUE THREAD

**Issue by bernease** [uwescience/DSSG2017-Equity#21]
The sources csv file indicates that there should be fields with links to the Seattle Open Data Portal, but it's not working. All seem to say "sources" but point to an empty href, which is just self.

**Comment by amanda-tan** [comment]
We need to go through and clean up source.csv and this will link the layers to the respective websites.

**Comment by amanda-tan** [comment]
Merged with https://github.com/uwescience/DSSG2017-Equity/issues/22
