### ISSUE TITLE
Upload geometry as GeoJSON

### ISSUE THREAD

**Issue by bernease** [uwescience/DSSG2017-Equity#3]
Upload geometry as GeoJSON (Hillary already uploaded bgs to GD), simplify shape at mapshaper.org

**Comment by bernease** [comment]
@hillary-dawkins, a cool tool to use to simplify the GeoJSON file is [http://mapshaper.org/](http://mapshaper.org/). You just upload your GeoJSON file to the webpage and can really reduce the filesize (making the website load faster).

Let me know if you have any questions about it!

**Comment by bernease** [comment]
We discussed offline limiting the geometry to the City of Seattle.

I'm now thinking it's better to use the block to neighborhood file from [the City of Seattle GIS webpage](https://www.seattle.gov/opcd/population-and-demographics/geographic-files-and-maps#2010census). The 5th column is block group (can confirm if non-unique). You could use this to filter the geometry.

Otherwise, you may consider the `consolidated+city` query option for the Census API.

## Documentation on Census ACS API

### General

https://www.census.gov/data/developers/data-sets/acs-5year.html

### Example list
http://api.census.gov/data/2015/acs5/examples.html

### Handcrafted example
http://api.census.gov/data/2015/acs5?get=NAME,B01001_001E&for=block+group:*&in=state:53&in=county:033

**Comment by hillary-dawkins** [comment]
@bernease I've added the census tract and neighborhood geo files  
you can only view one at a time but I've checked that they each display fine individually
